[workspace]
members = [
    "genesis_main",
    "core",
    "runtime",
    "memory",
    "planning",
    "tools",
    "plugin-sdk",
    "agent-desktop",
    "npc-runtime"
, "self_improvement",
 "cli_frontend",
 "tauri_frontend/src-tauri"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
